use crate::site::code_block;
use resuma::prelude::*;

pub fn page(_req: FlowRequest) -> View {
    view! {
        <>
            <h1>"Pages"</h1>
            <p class="lead">"Each page is a Rust module exporting pub fn page(FlowRequest) -> View, discovered from your pages directory."</p>

            <h2>"Page module"</h2>
            {code_block(r#"use resuma::prelude::*;

pub fn page(_req: FlowRequest) -> View {
    view! {
        <main>
            <h1>"About"</h1>
            <p>"Rendered from about.rs"</p>
        </main>
    }
}"#)}

            <h2>"auto_pages"</h2>
            <p>"FlowApp scans the pages directory at startup and dispatches via PagesRegistry:"</p>
            {code_block(r#"FlowApp::new()
    .auto_pages("src/pages", PagesRegistry)
    .serve(FlowServeOptions::default())
    .await"#)}

            <h2>"PagesRegistry"</h2>
            <p>"Generated by " <code>"resuma routes --generate"</code> ". Maps module names like " <code>"docs::getting_started"</code> " to " <code>"page(req)"</code> " functions."</p>
            {code_block(r#"// _registry.rs (generated)
impl FlowPageRegistry for PagesRegistry {
    fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
        match module {
            "index" => Some(super::index::page(req)),
            "about" => Some(super::about::page(req)),
            _ => None,
        }
    }
}"#)}

            <h2>"Index routes"</h2>
            <p>"A directory with index.rs maps to the directory URL — " <code>"blog/index.rs"</code> " becomes " <code>"/blog"</code>"."</p>
        </>
    }
}
